name: 'Depressed DST Modders GitHub Action'
description: "Run different modding tools for Don't Starve Together game"
author: 'Depressed DST Modders'
inputs:
  busted:
    default: 'false'
    description: 'Run Busted'
    required: false

  ldoc:
    default: 'false'
    description: 'Run LDoc'
    required: false

  luacheck:
    default: 'false'
    description: 'Run Luacheck'
    required: false

  prettier:
    default: 'false'
    description: 'Run Prettier'
    required: false

  stylua:
    default: 'false'
    description: 'Run StyLua'
    required: false

  slack:
    default: 'false'
    description: 'Enable Slack notification'
    required: false
  slack-color-default:
    default: '#1f242b'
    description: 'Default color for Slack attachment'
    required: false
  slack-color-failure:
    default: '#cc1f2d'
    description: 'Failure color for Slack attachment'
    required: false
  slack-color-success:
    default: '#24a943'
    description: 'Success color for Slack attachment'
    required: false
  slack-color-warning:
    default: '#dcad04'
    description: 'Warning color for Slack attachment'
    required: false
  slack-force-status:
    default: ''
    description: 'Force Slack status: success|failure|cancelled|skipped'
    required: false
  slack-luacheck-format:
    default: 'issues'
    description: 'Slack field format for Luacheck: issues|passes|failures'
    required: false
  slack-prettier-format:
    default: 'issues'
    description: 'Slack field format for Prettier: issues|passes|failures'
    required: false
  slack-stylua-format:
    default: 'issues'
    description: 'Slack field format for StyLua: issues|passes|failures'
    required: false

  ignore-check-versions:
    default: 'false'
    description: 'Ignore check versions step (disables versions output)'
    required: false
  ignore-failure:
    default: 'false'
    description: 'Ignore failures (action passes even when issues found or tests fail)'
    required: false
  ignore-set-output:
    default: 'false'
    description: 'Ignore set output step (disables all action output)'
    required: false
outputs:
  busted-version:
    description: 'Busted version'
  ldoc-version:
    description: 'LDoc version'
  lua-version:
    description: 'Lua version'
  luacheck-version:
    description: 'Luacheck version'
  prettier-version:
    description: 'Prettier version'
  stylua-version:
    description: 'StyLua version'

  busted-total:
    description: 'Number of total tests checked by Busted'
  busted-failed:
    description: 'Number of failed tests by Busted'
  busted-passed:
    description: 'Number of passed tests by Busted'
  busted-output:
    description: 'Busted output'

  ldoc-exit-code:
    description: 'Exit code of LDoc'
  ldoc-stderr:
    description: 'Standard error of LDoc'
  ldoc-stdout:
    description: 'Standard output of LDoc'

  luacheck-total:
    description: 'Number of total files checked by Luacheck'
  luacheck-failed:
    description: 'Number of failed files by Luacheck'
  luacheck-passed:
    description: 'Number of passed files by Luacheck'
  luacheck-issues:
    description: 'Number of total issues found by Luacheck'
  luacheck-output:
    description: 'The list of all failed files by Luacheck'

  prettier-total:
    description: 'Number of total files checked by Prettier'
  prettier-failed:
    description: 'Number of failed files by Prettier'
  prettier-passed:
    description: 'Number of passed files by Prettier'
  prettier-issues:
    description: 'Number of total issues found by Prettier'
  prettier-output:
    description: 'The list of all failed files by Prettier'

  stylua-total:
    description: 'Number of total files checked by StyLua'
  stylua-failed:
    description: 'Number of failed files by StyLua'
  stylua-passed:
    description: 'Number of passed files by StyLua'
  stylua-issues:
    description: 'Number of total issues found by StyLua'
  stylua-output:
    description: 'The list of all failed files by StyLua'
runs:
  using: 'docker'
  image: 'Dockerfile'
