name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  NODE_VERSION: 18
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_COLOR_FAILURE: '#cc1f2d'
  SLACK_COLOR_SUCCESS: '#24a943'
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1.2.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: in-progress
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --ignore-scripts
        env:
          NODE_ENV: development
      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1.2.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1.2.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: in-progress
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --ignore-scripts
        env:
          NODE_ENV: development
      - name: Lint
        run: yarn lint
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1.2.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1.2.0
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: in-progress
      - name: Prepare Code Climate
        if: ${{ !env.ACT }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --ignore-scripts
        env:
          NODE_ENV: development
      - name: Test
        id: test
        run: yarn test
      - name: Send Codecov report
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Send Code Climate report
        if: ${{ !env.ACT }}
        run: ./cc-test-reporter after-build --exit-code "$("${SUCCESS}" && echo 0 || echo 1)" --id ${{ secrets.CODE_CLIMATE_TOKEN }}
        env:
          SUCCESS: ${{ steps.test.outcome == 'success' }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1.2.0
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
